// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apbbymfdyfdaqflpivzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwYmJ5bWZkeWZkYXFmbHBpdnpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MTIwMTgsImV4cCI6MjA3ODE4ODAxOH0.-y5OtD5qwPulqOF7_3GaUk6avLqnU7D7D167VQeYICc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});